spring:
  application:
    name: DiscountCalculator
  security:
    user:
      name: admin
      password: admin



fx-service:
  exchange-rate-api:
    base-url: https://v6.exchangerate-api.com/v6
    api-key: b518ca71659758e9ae9c810f



